version: "3"
services:
  web:
    image: szabokaroly/get-started:0.0.2
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.1"
          memory: 30M
      restart_policy:
        condition: on-failure
    ports:
      - "88:80"
    networks:
      - webnet
networks:
  webnet:
